package com.jeff.isalev3.models

import kotlinx.serialization.Serializable

@Serializable
data class GetSalesResponse(
    val status: Boolean,
    val message: String?,
    val sales: List<SaleDetail>?,
)


@Serializable
data class SaleDetail(
    val id: Int,
    val print: String,
    val trdInvcNo: Int,
    val invcNo: Int,
    val orgInvcNo: Int,
    val custTin: String,
    val checksum: String?,
    val custNm: String,
    val salesTyCd: String,
    val rcptTyCd: String,
    val pmtTyCd: String,
    val salesSttsCd: String,
    val cfmDt: String,
    val salesDt: String,
    val stockRlsDt: String,
    val cnclReqDt: String?,
    val cnclDt: String?,
    val rfdDt: String?,
    val rfdRsnCd: String?,
    val totItemCnt: Int,
    val taxblAmtA: String,
    val taxblAmtB: String,
    val taxblAmtC: String,
    val taxblAmtD: String,
    val taxblAmtE: String,
    val taxRtA: String,
    val taxRtB: String,
    val taxRtC: String,
    val taxRtD: String,
    val taxRtE: String,
    val taxAmtA: String,
    val taxAmtB: String,
    val taxAmtC: String,
    val taxAmtD: String,
    val taxAmtE: String,
    val totTaxblAmt: String,
    val totTaxAmt: String,
    val totAmt: String,
    val prchrAcptcYn: String,
    val remark: String,
    val resultDt: String?,
    val curRcptNo: String?,
    val totRcptNo: String?,
    val intrlData: String?,
    val rcptSign: String?,
    val short_url: String?,
    val short_id: String?,
    val long_url: String?,
    val sdcDateTime: String?,
    val status: String,
    val createdAt: String,
    val updatedAt: String,
    val deletedAt: String?,
    val saleReceiptId: Int,
    val userId: Int,
    val businessId: Int,
    val items: List<ItemDetail>,
    val receipt: receipt
)

data class ItemDetail(
    val id: Int,
    val itemSeq: Int,
    val itemCd: String,
    val itemClsCd: String,
    val itemNm: String,
    val itemNmDef: String,
    val bcd: String?,
    val pkgUnitCd: String,
    val pkg: String,
    val qtyUnitCd: String,
    val qty: String,
    val prc: String,
    val splyAmt: String,
    val dcRt: String,
    val dcAmt: String,
    val taxTyCd: String,
    val taxblAmt: String,
    val taxAmt: String,
    val totAmt: String,
    val charges: Any?,  // You might want to specify a more precise type if known
    val status: String,
    val createdAt: String,
    val updatedAt: String,
    val deletedAt: String?,
    val salesId: Int,
    val itemId: Int
)